### ISSUE TITLE
loginButton UI Issue

### ISSUE THREAD

**Issue by aksbju** [putraxor/flutter-login-ui#1]
UI button looks great but overlay color couldn't fix there, that shows rectangular shape over circular edge button.
How to fix it?
![screenshot_20181220-130403](https://user-images.githubusercontent.com/44998751/50270576-00e2af80-0458-11e9-8071-9d36582bad2a.png)

**Comment by putraxor** [comment]
This issue has been fixed on [70a37cf](https://github.com/putraxor/flutter-login-ui/commit/67ef6e0aec0bf3e7a4e44d2d61721fce50a6b88d)
